name: Java 8 Build Jar

on:
  workflow_dispatch:  # 手动触发
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven

      # 构建打包
      - name: Build with Maven
        run: mvn clean package -DskipTests

      # 上传 jar
      - name: Upload JAR File
        uses: actions/upload-artifact@v4
        with:
          name: Canyon-Server
          path: target/*.jar
